star = print("      *"*2)
print("     * *"*2)
print("    *   *")
print("   *     *")
print("  *       *")
print(" *         *")
print("***       ***")
print("  *       *")
print("  *       *")
print("  *********")